[build]
  command = "sed -i \"s|API_PLACEHOLDER|${DEPLOY_PRIME_URL}|g\" netlify.toml && remix build"
  publish = "public"
  functions = "functions"

[context.deploy-preview.environment]
  API_URL = "API_PLACEHOLDER"

[dev]
  command = "remix watch"
  port = 3000
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
