[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[dev]
  command = "remix watch"
  port = 3000
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
